### ISSUE TITLE
Add an example listener

### ISSUE THREAD

**Issue by massdosage** [ExpediaGroup/drone-fly#4]
As a user of Drone Fly
I want an example listener that I can easily set up and configure without having to create my own
So that I can try out Drone Fly and verify that it works

h2. Acceptance Criteria
* A `LoggingListener` created in `drone-fly-app` that uses `slf4j` to log the parameters passed in every method call.
* README updated to describe this listener and how it can be used (how to configure, where to look for logs etc.) to test a new Drone Fly installation, making clear that this is just for debugging and verifying that it works etc. 

h2. Notes
I'm 99% sure that if we don't provide a logging config file then the default behavior is to log to the console but we should double check.

**Comment by abhimanyugupta07** [comment]
Solved via https://github.com/ExpediaGroup/drone-fly/pull/5
